[workspace]
channels = ["conda-forge"]
name = "classify_neurons"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.7.9.*"
pip = ">=24.0,<25"
setuptools = ">=69.0.3,<70"
wheel = ">=0.42.0,<0.43"
ca-certificates = ">=2025.6.15,<2026"
certifi = ">=2024.8.30,<2025"
openssl = ">=1.1.1w,<2"
cryptography = ">=38.0.2,<39"
cffi = ">=1.15.1,<2"
pycparser = ">=2.21,<3"
pyopenssl = ">=23.2.0,<24"
brotlipy = ">=0.7.0,<0.8"
urllib3 = ">=2.2.1,<3"
idna = ">=3.10,<4"
pysocks = ">=1.7.1,<2"
sqlite = ">=3.50.2,<4"
zlib = ">=1.3.1,<2"
git = ">=2.49.0,<3"
selenium = ">=4.15.1,<5"
six = ">=1.16.0,<2"
numpy = ">=1.21.6,<2"
python-dateutil = ">=2.9.0,<3"

[pypi-dependencies]
chardet = "==3.0.4"
colored = "==1.4.2"
fasteners = "==0.15"
gooey = "==1.0.4.0.0.0"
